default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: alealeale

development:
  <<: *default
  database: proyectoAlek_development

test:
  <<: *default
  database: proyectoAlek_test

production:
  <<: *default
  database: proyectoAlek_production
